[Brats17_TCIA_654_1_t2_unbiased.nii.gz, Brats17_CBICA_AAP_1_t2_unbiased.nii.gz, Brats17_TCIA_478_1_t2_unbiased.nii.gz, Brats17_CBICA_AVG_1_t2_unbiased.nii.gz, Brats17_TCIA_351_1_t2_unbiased.nii.gz, Brats17_CBICA_ASE_1_t2_unbiased.nii.gz, Brats17_CBICA_AUN_1_t2_unbiased.nii.gz, Brats17_2013_14_1_t2_unbiased.nii.gz, Brats17_CBICA_AVJ_1_t2_unbiased.nii.gz, Brats17_CBICA_AAL_1_t2_unbiased.nii.gz, Brats17_TCIA_493_1_t2_unbiased.nii.gz, Brats17_TCIA_322_1_t2_unbiased.nii.gz, Brats17_TCIA_325_1_t2_unbiased.nii.gz, Brats17_TCIA_620_1_t2_unbiased.nii.gz, Brats17_CBICA_AWG_1_t2_unbiased.nii.gz, Brats17_CBICA_AYW_1_t2_unbiased.nii.gz, Brats17_TCIA_274_1_t2_unbiased.nii.gz, Brats17_CBICA_BHK_1_t2_unbiased.nii.gz, Brats17_TCIA_254_1_t2_unbiased.nii.gz, Brats17_TCIA_420_1_t2_unbiased.nii.gz, Brats17_CBICA_AZH_1_t2_unbiased.nii.gz, Brats17_CBICA_ARW_1_t2_unbiased.nii.gz, Brats17_TCIA_618_1_t2_unbiased.nii.gz, Brats17_CBICA_ATX_1_t2_unbiased.nii.gz, Brats17_TCIA_429_1_t2_unbiased.nii.gz]
 Vae model:  camcan_400_Aug_6_100  NN model:  100subj_3e1_10steps_2fch2sh_xlaug_lr1_0_2
Using device: cuda:0
/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/serialization.py:593: SourceChangeWarning: source code of class 'networks.vae_bilinear_conv.ResBlock_Down' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/serialization.py:593: SourceChangeWarning: source code of class 'networks.vae_bilinear_conv.ResBlock_Up' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "restore_MAP_NN.py", line 67, in <module>
    net = torch.load(path, map_location=torch.device(device))
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/scratch_net/biwidl214/jonatank/logs/restore/100subj_3e1_10steps_2fch2sh_xlaug_lr1_0_2.pth'
