 Vae model:  VAE_400_40ep  NN model:  train_nn_dice_520
Using device: cuda:0
0.0907
0.0
Loading test set for subj
Subject  Brats17_CBICA_AMH_1_t2_unbiased.nii.gz  Number of Slices:  140
Traceback (most recent call last):
  File "restore_MAP_NN.py", line 142, in <module>
    error_batch_m = error_batch[mask > 0].ravel()
NameError: name 'error_batch_m' is not defined
